### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by rhythnic** [ahmed-masud/yo-express-polymer#1]
I'm getting this error while using the generator:

AssertionError: Trying to copy from a source that does not exist
{project_path}/node_modules/generator-polymer-middleware/generators/app/templates/._minimal-html/elements/._appname/._appname.html

**Comment by ahmed-masud** [comment]
can you please tell me the options you used when running the generator?

**Comment by rhythnic** [comment]
? Give your new polymer-express application a name: test-app
? Give your new polymer-express application a fancy title: Test App
? Give a starting version number: 0.0.0
? What license do you wish to distribute your application under? MIT
? What port do you want the server (bin/www) to run on (can also be a named pipe? What port do you want the server (bin/www) to run on (can also be a named pipe)? 3000
? Please specify a proxy port on which to run the server during development: (50? Please specify a proxy port on which to run the server during development: 5000
? Which express view (templating) engine do you wish to use? html
? Would you like to enable Passport.js for user management and session support? ? Would you like to enable Passport.js for user management and session support? ? Would you like to enable Passport.js for user management and session support? Yes
? Which template would you like to use for your app? minimal
? Which middleware do you prefer to use? Express
? Which back-end would you prefer to use? None
? Would you like me to skip npm install & bower install? No
copying editorconfig
copying jshintrc
copying bowerrc
copying yo-rc.json
copying wct.conf.json
copying _package.json
copying _bower.json
copying _gulpfile.js
copying bin/_www
copying ._minimal-html/elements/._appname/._appname.html

```
 _-----_
|       |    .-----------------------.
|--(o)--|    |      Bye from us!     |
```

   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /**_A**_\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   **'._**.'__  
 ´   `|° ´ Y` 

events.js:85
      throw er; // Unhandled 'error' event
            ^
AssertionError: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-polymer-middleware/generators/app/templates/._minimal-html/elements/._appname/._appname.html

**Comment by ahmed-masud** [comment]
Thank you, got it... i'll post a fix shortly.  Also, for now I'll be suppressing the KOA and HAPI engines until their templates are fully cooked.  You're using express, correct?

**Comment by ahmed-masud** [comment]
Hi,

I've just released v0.2.6 onto npm, please update your package and try again, it should yield proper results now.

**Comment by rhythnic** [comment]
Hi,

I updated the generator, and I'm still getting the same error, both with minimal template and polymer-starter-kit.

AssertionError: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-polymer-middleware/generators/app/templates/._polymer-starter-kit-html/elements/._appname/._appname.html

**Comment by AKRFranko** [comment]
I am having same issue. I have looked into my global node modules folder and I suspect the `.` is the culprit. The files do seem to exist but the names are NOT prefixed with dots. Could this be it?

**Comment by ahmed-masud** [comment]
Hi AKR,  are you generating these under windows?  If so I think that may be the issue and I can change the names in the template. I do think that it should work fine under there however could be the cause.  Please let me know.

Also please make sure you update the generator to 0.2.6 (or later)

**Comment by AKRFranko** [comment]
Nope. Arch Linux. 

`Linux 4.1.0-x86_64`

**Comment by ahmed-masud** [comment]
Hmmm... can you try share the choices that you made when running the
generator? (They're saved in package.json)

**Comment by ahmed-masud** [comment]
I believe that this issue is fixed in the latest version.

**Comment by itsashis4u** [comment]
I am getting the same error.

```
? Give your new polymer-express application a name: node-fyr
? Give your new polymer-express application a fancy title: App
? Give a starting version number: 0.0.0
? What license do you wish to distribute your application under? MIT
? What port do you want the server (bin/www) to run on (can also be a named pipe)? 3000
? Please specify a proxy port on which to run the server during development: 5000
? Which express view (templating) engine do you wish to use? html
? Would you like to enable Passport.js for user management and session support? Yes
? Which template would you like to use for your app? minimal
? Which middleware do you prefer to use? Express
? Which back-end would you prefer to use? MongoDB
? Would you like me to skip npm install & bower install? Yes
copying editorconfig
copying jshintrc
copying bowerrc
copying yo-rc.json
copying wct.conf.json
copying _package.json
copying _bower.json
copying _gulpfile.js
copying bin/_www
copying ._minimal-html/elements/._appname/._appname.html

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__   
 ´   `  |° ´ Y ` 


events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/generators/app/templates/._minimal-html/elements/._appname/._appname.html
    at EditionInterface.exports._copySingle (/home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)
    at null.<anonymous> (/home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/generators/app/index.js:54:19)
    at module.exports.yeoman.generators.Base.extend.writing.app (/home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/generators/app/index.js:220:18)
    at /home/ashish/.nvm/versions/node/v4.1.2/lib/node_modules/generator-polymer-middleware/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:374:17)

```
